### ISSUE TITLE
프로젝트 메인페이지 주소 변경안내

### ISSUE THREAD

**Issue by WAME-LEL** [WAME-LEL/OSSProject_RSSFeedWeb#12]
프로젝트의 메인 페이지 주소가 변경되었습니다.
기존: localhost:8000/latest/feed
변경 후: localhost:8000/
팀원들은 현재 글 확인하시고 확인 댓글 달아주시면 close 하겠습니다

**Comment by InMerchant** [comment]
난 확인했으니 강재 확인하고 닫아줘

**Comment by InMerchant** [comment]
남은 인원도 확인했으니 닫습네다
