### ISSUE TITLE
인터프리터 오류

### ISSUE THREAD

**Issue by InMerchant** [WAME-LEL/OSSProject_RSSFeedWeb#4]
파이참 인터프리터가 바꿔도 바뀌지 않는데 아는사람?

**Comment by WAME-LEL** [comment]
인터프리터가 여러 개 있어서 꼬인듯함. pycharm을 한번 재시작을 해보고 http://cbjsena.blogspot.com/2019/01/blog-post.html 이거 따라서 해보기

**Comment by InMerchant** [comment]
지우니까 해결완료.
