### ISSUE TITLE
장고 모델 필드 질문

### ISSUE THREAD

**Issue by InMerchant** [WAME-LEL/OSSProject_RSSFeedWeb#5]
models.TextField
models.URLField
우리 링크 저장할 때 url은 밑에 필드로 저장해야 되나?

**Comment by WAME-LEL** [comment]
URL을 DB에 저장할 때 models.TextField랑 models.URLField **둘 다 사용가능**한데 URLField를 사용하면 저장할 URL이 유효한(사용가능한) URL인지 확인하고 만약 유효하지 않은 URL이라면 DB에 저장하지 않는 등의 **후속처리가 가능**함.
TextField는 그런 처리가 불가능 하니 **URLField를 사용하는게 좋아 보임**
