### ISSUE TITLE
버전:bc2f50d 오류

### ISSUE THREAD

**Issue by leekj601** [WAME-LEL/OSSProject_RSSFeedWeb#9]
html을 통해 데이터 베이스 url 불러오기는 성공.
근데 url 관련 오류인지 sub.html에는 적용 실패

**Comment by WAME-LEL** [comment]
수정 완료
-render 함수의 세번째 파라미터에는 렌더링 할 html 파일로 보낼 데이터를 넣을 수 있음. 데이터를 제대로 보내지 않아서 html에서 아무런 값이 나오지 않았던 것
